### ISSUE TITLE
Config file is not published

### ISSUE THREAD

**Issue by aeq-dev** [sfolador/laravel-locked#4]
Laravel 9
`INFO  No publishable resources for tag [laravel-locked-config].`

**Comment by sfolador** [comment]
Thanks! I will fix this as soon as possible or.. if you want you can open a PR and propose the solution yourself. It will be really appreciated.

**Comment by sfolador** [comment]
Closed with commit b80858ac99c55c058a8b27f3c6c4715916c16ce5.
